# Generated by Django 5.2.18 on 2026-10-09 05:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]*$', 'Usa letras mayúsculas, números, puntos o guiones.')])),
                ('description', models.TextField(max_length=1500)),
                ('category', models.CharField(choices=[('prendas', 'Prendas'), ('regalos', 'Regalos'), ('textiles', 'Textiles'), ('piezas-3d', 'Piezas 3D')], max_length=16)),
                ('technique_key', models.CharField(choices=[('sublimacion', 'Sublimación'), ('dtf', 'DTF'), ('3d', 'Impresión 3D'), ('personalizacion', 'Personalización')], max_length=20)),
                ('image', models.CharField(default='images/collection-concept.webp', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('MXN', 'Peso mexicano')], default='MXN', max_length=3)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_concept', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='product_price_nonnegative')],
            },
        ),
    ]
